"""initial_voice_schema

Revision ID: 38d069d34930
Revises: 
Create Date: 2026-04-19 02:43:35.153408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d069d34930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('voice_id')
    )
    op.create_table('voice_labels',
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.voice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voice_id', 'key')
    )
    op.create_table('voice_stats',
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('total_audio_seconds', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['voice_id'], ['voices.voice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_stats')
    op.drop_table('voice_labels')
    op.drop_table('voices')
    # ### end Alembic commands ###
